Resources:
  userTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userTable}
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: roomId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ${self:custom.roomIndex}
          KeySchema:
            - AttributeName: roomId
              KeyType: HASH
            - AttributeName: connectionId
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - username
            ProjectionType: INCLUDE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  messageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.messageTable}
      AttributeDefinitions:
        - AttributeName: roomId
          AttributeType: S
        - AttributeName: dateTime
          AttributeType: N
      KeySchema:
        - AttributeName: roomId
          KeyType: HASH
        - AttributeName: dateTime
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
